### ISSUE TITLE
业务只返回statuscode没有body的时候报错

### ISSUE THREAD

**Issue by RobinzZH** [Tencent/TSW#384]
代码位置：
e.g.
https://github.com/Tencent/TSW/blob/master/lib/core/runtime/create-server.hack.ts#L118

报错堆栈：

```js
/Users/xxx/xxx/xxx/node_modules/@tswjs/tsw/dist/core/runtime/create-server.hack.js:98
                        responseBody: res._body.toString("base64"),
                                                ^

TypeError: Cannot read property 'toString' of undefined
    at ServerResponse.<anonymous> (/Users/xxx/xxx/xxx/node_modules/@tswjs/tsw/dist/core/runtime/create-server.hack.js:98:49)
    at Object.onceWrapper (events.js:312:28)
    at ServerResponse.emit (events.js:228:7)
    at ServerResponse.EventEmitter.emit (domain.js:498:23)
    at onFinish (_http_outgoing.js:686:10)
    at onCorkedFinish (_stream_writable.js:715:5)
    at afterWrite (_stream_writable.js:522:5)
    at afterWriteTick (_stream_writable.js:509:10)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

```

**Comment by mapleeit** [comment]
2.0.0-alpha.2 版本已经修复此问题
